#!/bin/sh
for file in $(find src/pages/admin src/layouts/AdminLayout.tsx -name "*.tsx"); do
  sed -i 's/\bbg-white\b/bg-slate-900/g' "$file"
  sed -i 's/\bbg-slate-50\b/bg-slate-800/g' "$file"
  sed -i 's/\bbg-slate-100\b/bg-slate-950/g' "$file"
  sed -i 's/\bbg-gray-50\b/bg-slate-800/g' "$file"
  sed -i 's/\bbg-gray-100\b/bg-slate-950/g' "$file"
  sed -i 's/\bbg-slate-100\/50\b/bg-slate-900\/50/g' "$file"
  sed -i 's/\bbg-slate-50\/50\b/bg-slate-800\/50/g' "$file"
  sed -i 's/\bbg-slate-200\/50\b/bg-slate-800\/50/g' "$file"
  sed -i 's/\btext-slate-900\b/text-white/g' "$file"
  sed -i 's/\btext-slate-800\b/text-slate-100/g' "$file"
  sed -i 's/\btext-slate-700\b/text-slate-200/g' "$file"
  sed -i 's/\btext-slate-600\b/text-slate-300/g' "$file"
  sed -i 's/\btext-slate-500\b/text-slate-400/g' "$file"
  sed -i 's/\btext-gray-900\b/text-white/g' "$file"
  sed -i 's/\btext-gray-800\b/text-slate-100/g' "$file"
  sed -i 's/\bborder-slate-200\b/border-slate-800/g' "$file"
  sed -i 's/\bborder-slate-300\b/border-slate-700/g' "$file"
  sed -i 's/\bborder-gray-200\b/border-slate-800/g' "$file"
  sed -i 's/\bdivide-slate-200\b/divide-slate-800/g' "$file"
  sed -i 's/\bhover:bg-slate-50\b/hover:bg-slate-800/g' "$file"
  sed -i 's/\bhover:bg-slate-100\b/hover:bg-slate-800/g' "$file"
  sed -i 's/\bactive:bg-slate-100\b/active:bg-slate-800/g' "$file"
  sed -i 's/\btext-black\b/text-white/g' "$file"
done
